SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE FRIENDS      RESTART IDENTITY;
TRUNCATE TABLE FILMS_GENRE  RESTART IDENTITY;
TRUNCATE TABLE GENRE        RESTART IDENTITY;
TRUNCATE TABLE FILM_LIKES   RESTART IDENTITY;
TRUNCATE TABLE FILMS        RESTART IDENTITY;
TRUNCATE TABLE MPA_RATING   RESTART IDENTITY;
TRUNCATE TABLE USERS        RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO GENRE (GENRE_NAME)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');

INSERT INTO MPA_RATING (MPA_NAME)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');